### ISSUE TITLE
Docker installation error: No matching distribution found for intel-openmp (from deeplabcut) 

### ISSUE THREAD

**Issue by ambareeshsrja16** [DeepLabCut/Docker4DeepLabCut2.0#25]
Was using the latest Dockerfile and got this error:

ERROR: Could not find a version that satisfies the requirement intel-openmp (from deeplabcut) (from versions: none)
ERROR: No matching distribution found for intel-openmp (from deeplabcut)
The command '/bin/sh -c pip3 install deeplabcut' returned a non-zero code: 1

I saw in other posts that this error pops up during installation in MacOS systems. But I am installing it on a Docker (on an Ubuntu machine, don't know if that even matters) 

Any pointers?

**Comment by MMathisLab** [comment]
I had this happen recently with the latest pip; rolling back to < 19 helped, so just delete the line in the Docker file that says upgrade pip

**Comment by ambareeshsrja16** [comment]
Worked like a charm! Man! you guys are so amazingly responsive! I was telling my lab folks that probably I'll lose an entire day chasing this error! Thank you so much!  :)

I'll update the other thread as well!
