### ISSUE TITLE
ModuleNotFoundErrot: No module named 'numpy.testing.decorators'

### ISSUE THREAD

**Issue by prnvkhndlwl** [DeepLabCut/Docker4DeepLabCut2.0#26]
Hey!

So I started on a fresh installation of ubuntu 18.04 and everything worked including building the docker image and entering the docker container. However, when inside the container -
export DLClight=True -> works
ipython -> works
import deeplabcut -> I get the following error 

> prnv@8f1fe0ba761e:/$ export DLClight=True
> prnv@8f1fe0ba761e:/$ ipython
> Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
> Type 'copyright', 'credits' or 'license' for more information
> IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: import deeplabcut
> DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-cfa4f159dfc5> in <module>()
> ----> 1 import deeplabcut
> 
> /usr/local/lib/python3.6/dist-packages/deeplabcut/__init__.py in <module>()
>      41     print("Project loaded in colab-mode. Apparently Colab has trouble loading statsmodels, so the smoothing & outlier frame extraction is disabled. Sorry!")
>      42 else:
> ---> 43     from deeplabcut.refine_training_dataset import extract_outlier_frames, merge_datasets
>      44     from deeplabcut.post_processing import filterpredictions, analyzeskeleton
>      45 
> 
> /usr/local/lib/python3.6/dist-packages/deeplabcut/refine_training_dataset/__init__.py in <module>()
>      18     from deeplabcut.refine_training_dataset.auxfun_drag import *
>      19 
> ---> 20 from deeplabcut.refine_training_dataset.outlier_frames import *
> 
> /usr/local/lib/python3.6/dist-packages/deeplabcut/refine_training_dataset/outlier_frames.py in <module>()
>      14 from pathlib import Path
>      15 import pandas as pd
> ---> 16 import statsmodels.api as sm
>      17 from deeplabcut.utils import auxiliaryfunctions, visualization
>      18 from deeplabcut.utils import frameselectiontools
> 
> /usr/local/lib/python3.6/dist-packages/statsmodels/api.py in <module>()
>       5 from . import tools
>       6 from .tools.tools import add_constant, categorical
> ----> 7 from . import regression
>       8 from .regression.linear_model import OLS, GLS, WLS, GLSAR
>       9 from .regression.recursive_ls import RecursiveLS
> 
> /usr/local/lib/python3.6/dist-packages/statsmodels/regression/__init__.py in <module>()
> ----> 1 from .linear_model import yule_walker
>       2 
>       3 from statsmodels.tools._testing import PytestTester
>       4 
>       5 __all__ = ['yule_walker', 'test']
> 
> /usr/local/lib/python3.6/dist-packages/statsmodels/regression/linear_model.py in <module>()
>      38 import numpy as np
>      39 from scipy.linalg import toeplitz
> ---> 40 from scipy import stats
>      41 from scipy import optimize
>      42 
> 
> /usr/local/lib/python3.6/dist-packages/scipy/stats/__init__.py in <module>()
>     343 from .stats import *
>     344 from .distributions import *
> --> 345 from .morestats import *
>     346 from ._binned_statistic import *
>     347 from .kde import gaussian_kde
> 
> /usr/local/lib/python3.6/dist-packages/scipy/stats/morestats.py in <module>()
>      10                    sqrt, ceil, floor, array, compress,
>      11                    pi, exp, ravel, count_nonzero, sin, cos, arctan2, hypot)
> ---> 12 from numpy.testing.decorators import setastest
>      13 
>      14 from scipy._lib.six import string_types
> 
> ModuleNotFoundError: No module named 'numpy.testing.decorators'
> 

Any suggestions? 

Also a sidenote -
on ubuntu 18.04
'sudo apt-get install nvidia-docker' seems to not work but 'sudo apt-get install nvidia-docker2' does the job!

Thank you so much! :)

**Comment by sbtnRey** [comment]
I had the same issue recently, "pip install numpy==1.16.4" in the container seemed to fix it.

**Comment by prnvkhndlwl** [comment]
It worked! Thank you so much for the quick response!!!

**Comment by som21-star** [comment]
> I had the same issue recently, "pip install numpy==1.16.4" in the container seemed to fix it.

Great!!...recently, I had the same issue. Now it's fixed. Thanks buddy.

**Comment by Krishna-Sarath-Maddula** [comment]
> I had the same issue recently, "pip install numpy==1.16.4" in the container seemed to fix it.

Worked. Thanks a lot!

**Comment by scollay** [comment]
Same here - pip'd something and it broke everything upgrading to 1.18.5
Back to 1.16.4 and all fine.
Thanks!

**Comment by pnidhi26** [comment]
Thanks, its work for me. New update over numpy 1.19 version have some issue but lower versions work perfectly.

**Comment by chetan11-stack** [comment]
> I had the same issue recently, "pip install numpy==1.16.4" in the container seemed to fix it.

Thank you!!
