### ISSUE TITLE
./dlc-docker: line 179: nvidia-docker: command not found

### ISSUE THREAD

**Issue by M3-Coordinator** [DeepLabCut/Docker4DeepLabCut2.0#36]
I am trying to run the docker image on Pop!_OS 20.04, with NVIDIA 455.38, GeForse RTX 2070.
I have the latest nvidia-container-toolkit from the Pop!_OS repositories, which I am assured is the same as the latest NVIDIA for Ubuntu 20.04, .
I also have the latest Docker from the repositories, version 19.03.13, build 4484c46d9d.
`nvidia-smi` shows that my gpu is '0'.
I setup according to the readme, but when I get to the command:
`GPU=0 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut --name dlcContainer kdys/dlcdocker`
I get the following:
```
ret run -d -p 2351:8888 -e USER_HOME=/home/kdys/DeepLabCut --name dlcContainer kdys/dlcdocker run
1st CMD run

* Setting user name to:             kdys
* Setting user ID to:               1000
* Setting user groups to:           sudo
* Setting password to:              pw
* Setting Notebook port binding to: 2351 (to set manually add -p 2351:8888 as flag)

You can now open the notebook on the host machine by directing your browser to

    http://localhost:2351

0 nvidia-docker run -v /home/kdys:/home/kdys -p 35053:22 -p 2351:8888 -e USER_GROUPS=sudo -e USER=kdys -e USER_ID=1000 -e USER_ENCRYPTED_PASSWORD=aa5V9MSdgw5ec -e USER_HOME=/home/kdys -e GPU=0 -e DISPLAY=:1 -d -e USER_HOME=/home/kdys/DeepLabCut --name dlcContainer kdys/dlcdocker
./dlc-docker: line 179: nvidia-docker: command not found
```
A little searching has led me to understand that "nvidia-docker" command is deprecated.
I tried to install nvidia-docker2 as suggested here [https://github.com/NVIDIA/nvidia-docker/issues/1028](url), but I am met with:
`E: Unable to locate package nvidia-docker2`

Is anyone running this on Ubuntu 20.04? And if so how do we bypass the depricated nvidia-docker command?
Thanks

**Comment by MMathisLab** [comment]
i assure you it runs on ubuntu 20.04 LTS; docker is natively installed there, so I don't know your specific issue. As I mentioned on the forum, I think fist thing was to fix the paths, then see if the issue persists. I know nothing of Pop! OS, sorry! 

Of course, as we say if you have ubuntu pre20, these commands much be installed first:
```
$ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
sudo apt-key add -
$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
$ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
sudo tee /etc/apt/sources.list.d/nvidia-docker.list
$ sudo apt-get update

$ sudo apt-get install nvidia-docker2
```

**Comment by dysonsphere-startmail** [comment]
Thanks for taking the time to help with this.
I entered the above commands (had to enter ubuntu20.04 as pop20.04 came up as "unsupported distribution").
Was able to install nvidia-docker2
now running:
`GPU=0 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut --name dlcContainer kdys/dlcdocker
ret run -d -p 2351:8888 -e USER_HOME=/home/kdys/DeepLabCut --name dlcContainer kdys/dlcdocker run`
gives me a different error:
```
1st CMD run

* Setting user name to:             kdys
* Setting user ID to:               1000
* Setting user groups to:           sudo
* Setting password to:              pw
* Setting Notebook port binding to: 2351 (to set manually add -p 2351:8888 as flag)

You can now open the notebook on the host machine by directing your browser to

    http://localhost:2351

0 nvidia-docker run -v /home/kdys:/home/kdys -p 57908:22 -p 2351:8888 -e USER_GROUPS=sudo -e USER=kdys -e USER_ID=1000 -e USER_ENCRYPTED_PASSWORD=aa5V9MSdgw5ec -e USER_HOME=/home/kdys -e GPU=0 -e DISPLAY=:1 -d -e USER_HOME=/home/kdys/DeepLabCut --name dlcContainer kdys/dlcdocker
docker: Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'.
```

**Comment by dysonsphere-startmail** [comment]
Shoot. I just needed to restart Docker after installing  nvidia-docker2.
Thanks so much!
